spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CustomerMS
          uri: lb://CustomerMS
          predicates:
            - Path=/customer/**
        - id: OfferMS
          uri: lb://OfferMS
          predicates:
            - Path=/offers/**
        - id: WalletMS
          uri: lb://WalletMS
          predicates:
            - Path=/wallet/**